#!/usr/bin/python3
import sys

# removeNames.py - Substitutes the names of the images on .dat files generated by
# extractFeatures.py (and also selectFeatures.dat) by their classes (0 - authentic, 1 - tampered)
# Receives the input and output dat files as argument.

inFile, outFile = sys.argv[1], sys.argv[2]
of = open(outFile, "w")

with open(inFile) as f:
	lines = f.readlines()

for line in lines:
	parts = line.split()
	if parts[0][0] == 'T':
		parts[0] = "1"
	else:
		parts[0] = "0"
	of.write(' '.join(parts) + '\n')
of.close()
